name: Build
run-name: ${{ github.actor }} start build webApp 🚀
on:
  pull_request:
    types: [synchronize, closed, opened]
    branches:
      - dev
      - master

jobs:
  Web-App-Build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Trigger web-app build on ${{ github.event_name }} event."
      - run: echo "Checkout to yourbranch ${{ github.ref }}."