name: Build
run-name: ${{ github.actor }} start build webApp 🚀
on:
  pull_request:
    types: [synchronize, closed, opened]
    branches:
      - dev
      - master
  
jobs:
  build-web-app:
    name: 'Build web app'
    runs-on: ubuntu-latest
    steps:
      - name: Get details
        run: |
          echo "Trigger web-app build on ${{ github.event_name }} event."
          echo "Checkout to yourbranch ${{ github.ref }}."

      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Restore cached
        id: cache-restore
        uses: actions/cache@v3
        with:
          path: '**/node_modules'
          key: yarn-${{ github.base_ref }}-${{ hashFiles('./yarn.lock') }}
          restore-keys: yarn-${{ github.base_ref }}


      - name: Install the dependencies
        run: |
          echo "Installing the dependancies on ${{ runner.os }} server hosted by GitHub!"
          yarn

      - name: build webpack
        run : yarn build-webpack