name: Build
run-name: ${{ github.actor }} start build webApp 🚀
on:
  pull_request:
    types: [synchronize, closed, opened]
    branches:
      - dev
      - master
  
jobs:
  build-web-app:
    if: !github.event.pull_request.merged
    name: 'Build web app'
    runs-on: ubuntu-latest
    steps:
      - name: Get details
        run: |
          echo "Trigger web-app build on ${{ github.event_name }} event."
          echo "Checkout to yourbranch ${{ github.ref }}."

      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Restore cached
        id: cache-restore
        uses: actions/cache@v3
        with:
          path: |
            **/node_modules
            temp.text
          key: yarn-${{ github.base_ref }}-${{ hashFiles('./yarn.lock') }}
          restore-keys: yarn-${{ github.base_ref }}

      - name: Install the dependencies
        run: |
          echo "Installing the dependancies on ${{ runner.os }} server hosted by GitHub!"
          yarn

      - name: build webpack
        run : yarn build-webpack

      - name: Restore ${{ github.base_ref }}-stats.json from cached
        id: stats-restore
        uses: actions/cache@v3
        with:
          path: '${{ github.base_ref }}-stats.json'
          key: stats-${{ github.base_ref }}-${{ github.event.pull_request.base.sha }}

      - name: Check file existence
        id: check_files
        uses: andstor/file-existence-action@v1
        with:
          files: '${{ github.base_ref }}-stats.json'

      - name: Diff between base & head
        if: steps.check_files.outputs.files_exists == 'true'
        uses: chronotruck/webpack-stats-diff-action@1.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base_stats_path: ${{ github.base_ref }}-stats.json
          head_stats_path: app/build/stats.json

  cleanup:
    name: 'Cleanup Caches'
      if: github.event.pull_request.merged
      runs-on: ubuntu-latest
      steps:
        - name: Get details
          run: |
            echo "Trigger web-app build on ${{ github.event_name }} event."
            echo "Checkout to yourbranch ${{ github.ref }}."

        - name: Delete cache
          uses: snnaplab/delete-branch-cache-action@v1
          with:
            # Specify explicitly because the ref at the time of merging will be a branch name such as 'main', 'develop'
            ref: refs/pull/${{ github.event.number }}/merge
