name: Build
run-name: ${{ github.actor }} start build webApp 🚀
on:
  pull_request:
    types: [synchronize, closed, opened]
    branches:
      - dev
      - master
  
jobs:
  build-web-app:
    runs-on: ubuntu-latest
    steps:
      - name: Get details
        run: |
          echo "Trigger web-app build on ${{ github.event_name }} event."
          echo "Checkout to yourbranch ${{ github.ref }}."

      - name: Check out repository code
        uses: actions/checkout@v3
        
      - name: Cache
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        uses: actions/cache@v2.1.8
        with:
          # A list of files, directories, and wildcard patterns to cache and restore
          path: "./node_modules"
          key: yarn-${{ hashFiles('./yarn.lock') }}
        
      - name: Install the dependencies
        run: |
          echo "Installing the dependancies on ${{ runner.os }} server hosted by GitHub!"
          yarn

      - name: build webpack
        run : yarn build-webpack

      - name: Run bundle-stats
        uses: vio/bundle-stats-action@v1
        with:
          webpack-stats-path: 'app/build/stats.json'
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload stats.json
        uses: actions/upload-artifact@v1
        with:
          name: build-head
          path: 'app/build/stats.json'

  build-base-web-app:
    name: 'Build base'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ## Here we do not checkout the current branch, but we checkout the base branch.
          ref: ${{ github.base_ref }}

      - name: Cache
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        uses: actions/cache@v2.1.8
        with:
          # A list of files, directories, and wildcard patterns to cache and restore
          path: "./node_modules"
          key: yarn-${{ hashFiles('./yarn.lock') }}

      - name: Install the dependencies
        run: |
          echo "Installing the dependancies on ${{ runner.os }} server hosted by GitHub!"
          yarn

      - name: build webpack
        run: yarn build-webpack

      - name: Upload stats.json
        uses: actions/upload-artifact@v1
        with:
          name: build-base
          path: 'app/build/stats.json'

  compare:
    name: 'Compare base & head bundle sizes'
    runs-on: ubuntu-latest
    needs: [ build-web-app, build-base-web-app ]
    steps:
      - uses: actions/checkout@v1
      - name: Download base artifact
        uses: actions/download-artifact@v1
        with:
          name: base-stats
      - name: Download head artifact
        uses: actions/download-artifact@v1
        with:
          name: head-stats
      - name: Diff between base & head
        uses: chronotruck/webpack-stats-diff-action@1.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base_stats_path: ./base-stats/stats.json
          head_stats_path: ./head-stats/stats.json