name: Build
run-name: ${{ github.actor }} start build webApp 🚀
on:
  pull_request:
    types: [synchronize, closed, opened]
    branches:
      - dev
      - master
  
jobs:
  build-web-app:
    if: github.event.pull_request.merged == false
    name: 'Build web app'
    runs-on: ubuntu-latest
    steps:
      - name: Get details
        run: |
          echo "Trigger web-app build on ${{ github.event_name }} event."
          echo "Checkout to yourbranch ${{ github.ref }}."

      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Get head ref
        env:
          head_ref: ${{ github.head_ref }}
        run: |
          echo HEAD_REF=$head_ref | sed -r 's/[\/]+/-/g' >> $GITHUB_ENV

      - name: Restore cached
        id: cache-restore
        uses: actions/cache/restore@v3
        with:
          path: |
            **/node_modules
            ${{ github.base_ref }}-stats.json
          key: |
            yarn-${{ github.head_ref }}
          restore-keys: |
            cache-${{ github.base_ref }}

      - name: Install the dependencies
        run: |
          echo "Installing the dependancies on ${{ runner.os }} server hosted by GitHub!"
          yarn

      - name: build webpack
        run : yarn build-webpack

      - name: Check file existence
        id: check_files
        uses: andstor/file-existence-action@v1
        with:
          files: '${{ github.base_ref }}-stats.json'

      - name: Cleanup ${{ github.ref_name }} cache
        uses: snnaplab/delete-branch-cache-action@v1
        with:
          ref: refs/pull/${{ github.event.number }}/merge

      - name: save cache
        uses: actions/cache/save@v3
        with:
          path: |
            **/node_modules
            ${{ github.base_ref }}-stats.json
          key: yarn-${{ github.head_ref }}

      - name: Diff between base & head
        if: steps.check_files.outputs.files_exists == 'true'
        uses: chronotruck/webpack-stats-diff-action@1.0.0
        with:
          title: Compate bunddle size
          token: ${{ secrets.GITHUB_TOKEN }}
          base_stats_path: ${{ github.base_ref }}-stats.json
          head_stats_path: app/build/stats.json

      - name: Diff between base & head 2
        uses: github/webpack-bundlesize-compare-action@v1.5.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          current-stats-json-path: app/build/stats.json
          base-stats-json-path: ${{ github.base_ref }}-stats.json

  cleanup:
    if: github.event.pull_request.merged
    name: 'Cleanup Caches'
    runs-on: ubuntu-latest
    steps:
      - name: Get details
        run: |
          echo "Trigger web-app build on ${{ github.event_name }} event."
          echo "Checkout to yourbranch ${{ github.ref }}."

      - name: Delete cache
        uses: snnaplab/delete-branch-cache-action@v1
        with:
          ref: refs/pull/${{ github.event.number }}/merge
