name: Cache base branch files
run-name: Start cache ${{ github.ref }}
on:
  push:
    branches: [ 'dev', 'master' ]
jobs:
  build-web-app-cache:
    runs-on: ubuntu-latest
    steps:
    - name: Get details
      run: |
        echo "Trigger web-app build on ${{ github.event_name }} event."
        echo "Checkout to yourbranch ${{ github.ref_name }}."

    - name: Check out repository code
      uses: actions/checkout@v3

    - name: yarn cache
      id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
      uses: actions/cache@v3
      with:
        # A list of files, directories, and wildcard patterns to cache and restore
        path: |
          **/node_modules
        key: yarn-${{ github.ref_name }}-${{ hashFiles('./yarn.lock') }}
        restore-keys: yarn-${{ github.ref_name }}

    - name: Install the dependencies
      run: |
        echo "Installing the dependancies on ${{ runner.os }} server hosted by GitHub!"
        yarn

    - name: build webpack
      run: yarn build-webpack

    - name: Copy stats.json
      run: |
        echo 'Copying app/build/stats.json -> ${{ github.ref_name }}-stats.json'
        cp 'app/build/stats.json' '${{ github.ref_name }}-stats.json'

    - name: yarn cache
      id: stats-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
      uses: actions/cache@v3
      with:
        # A list of files, directories, and wildcard patterns to cache and restore
        path: |
          ${{ github.ref_name }}-stats.json
        key: stats-${{ github.ref_name }}-${{ github.sha }}
