name: Cache base branch files
run-name: Start cache ${{ github.ref }}
on:
  push:
    branches: [ 'dev', 'master' ]
jobs:
  build-web-app-cache:
    runs-on: ubuntu-latest
    steps:
    - name: Get details
      run: |
        echo "Trigger web-app build on ${{ github.event_name }} event."
        echo "Checkout to yourbranch ${{ github.ref_name }}."

    - name: Check out repository code
      uses: actions/checkout@v3

    - name: Check yarn cache
      id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
      uses: actions/cache@v3
      with:
        # A list of files, directories, and wildcard patterns to cache and restore
        path: |
          './node_modules'
          'app/build/stats.json'
        key: yarn-${{ github.ref_name }}
        restore-keys: yarn-${{ github.ref_name }}

    - name: Install the dependencies
      run: |
        echo "Installing the dependancies on ${{ runner.os }} server hosted by GitHub!"
        yarn

    - name: build webpack
      run: yarn build-webpack

    - name: Upload stats.json
      uses: actions/upload-artifact@v2
      with:
        name: stats-${{ github.ref_name }}
        path: 'app/build/stats.json'
        retention-days: 20

