name: Cache base branch files
run-name: Start cache ${{ github.ref }}
on:
  push:
    branches: [ 'dev', 'master' ]
jobs:
  build-web-app-cache:
    runs-on: ubuntu-latest
    steps:
    - name: Get details
      run: |
        echo "Trigger web-app build on ${{ github.event_name }} event."
        echo "Checkout to yourbranch ${{ github.head_ref }}."

    - name: Check out repository code
      uses: actions/checkout@v3

    - name: Check yarn cache
      id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
      uses: actions/cache@v2.1.8
      with:
        # A list of files, directories, and wildcard patterns to cache and restore
        path: "./node_modules"
        key: yarn-${{ github.head_ref }}-${{ hashFiles('./yarn.lock') }}
        restore-keys: yarn-${{ github.head_ref }}

    - name: Install the dependencies
      run: |
        echo "Installing the dependancies on ${{ runner.os }} server hosted by GitHub!"
        yarn

    - name: build webpack
      run: yarn build-webpack

    - name: Upload stats.json
      uses: actions/upload-artifact@v2
      with:
        name: stats-${{ github.head_ref }}-${{ github.sha }}
        path: 'app/build/stats.json'
        retention-days: 20

